#ifndef QMGUILIB_GLOBAL_H
#define QMGUILIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QMGUILIB_LIBRARY)
#  define QMGUILIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QMGUILIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QMGUILIB_GLOBAL_H
